version: '2'

volumes:
  odoo_data: {}
  pgsql_data: {}

networks:
  odoonet:
    driver: bridge

services:
  postgresql:
    image: 'dimaskiddo/alpine:postgresql-9.6'
    networks:
      - odoonet
    ports:
      - 5432:5432
    user: root
    environment:
      - POSTGRESQL_USER=odoo
      - POSTGRESQL_PASSWORD=odoo
      - POSTGRESQL_ROOT_PASSWORD=odoo
      - POSTGRESQL_DATABASE=odoo
    volumes:
      - pgsql_data:/var/lib/pgsql/data
    restart: always

  odoo:
    image: 'dimaskiddo/ubuntu:odoo-10.0'
    networks:
      - odoonet
    ports:
      - 8069:8069
    user: root
    environment:
      - ODOO_DB_HOST=postgresql
      - ODOO_DB_PORT=5432
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
    volumes:
      - odoo_data:/var/lib/odoo
      - ./addons/odoo:/mnt/odoo/addons
      - ./configs/odoo/odoo.conf:/etc/odoo/odoo.conf
    depends_on:
      - postgresql
    restart: always

  nginx:
    image: 'dimaskiddo/alpine:nginx-1.12.2-novol'
    networks:
      - odoonet
    ports:
      - 80:8080
      - 443:8443
    user: root
    volumes:
      - ./configs/nginx/conf.d/default.conf:/var/www/data/etc/nginx/conf.d/default.conf
      - ./configs/nginx/certs/odoo_localhost.key:/etc/ssl/private/odoo_localhost.key
      - ./configs/nginx/certs/odoo_localhost.crt:/etc/ssl/certs/odoo_localhost.crt
      - ./configs/nginx/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
    depends_on:
      - odoo
    restart: always
