version: '2'

networks:
  odoonet:
    driver: bridge

services:
  postgresql:
    image: dimaskiddo/debian-buster:postgresql-11
    networks:
      - odoonet
    env_file: ./env/postgresql.env
    volumes:
      - ./data/postgresql:/var/lib/pgsql/data
    restart: unless-stopped

  odoo:
    image: 'dimaskiddo/debian-buster:odoo-15.0'
    networks:
      - odoonet
    ports:
      - 8069:8069
      - 8072:8072
    env_file: ./env/odoo.env
    volumes:
      - ./data/odoo/data:/var/lib/odoo
    depends_on:
      - postgresql
    restart: unless-stopped
